Goodbye Dear Old Stepstone: Country Grubbin'
<br />
Songs about chicken pie, greasy greens, watermelon, porkchops, big biscuits, tasty gravy, red ripe tomatoes and... you get the idea? There's enough naughty imagery to make any peach picker blush in this collection from Nathan Salsburg. With Uncle Dave Macon, Peg Leg Sam, Doodle Thrower & Golden River Grass, Bo Carter, Jack Kelly's Jug Band, others.
(37 minutes)
