Goodbye Dear Old Stepstone: Lining Hymns 
<br />
The practice of "lining out" hymns was the dominant form of congregational singing before musical instruments, organized choirs, and increased literacy made lining obsolete. It has endured in only a handful of marginal but proud places: among the Primitive Baptists of Appalachia; in black Baptist and a handful of Presbyterian churches in the deep South; and the Gaelic Presbyterians of the Western Isles of Scotland. --Nathan Salsburg
<br /><br />
Samples from George Spangler & the congregation of the Thornton Old Regular Baptist Church, Mayking KY, Rev. J.M. Gates & Singers, Rev. G. I. Townsel & congregation, John Murdo Martin (of Portree) & Singers, and five others. (35 minutes) 
