Goodbye Dear Old Stepstone: Songs for Memorial Day 
<br />
They may war by day, they may war by night<br />
They can bring the atomic bomb<br />
But the devil and the pilot can't make me run
<br /><br />
I don't want to fight, I don't want to war<br />
I want food to eat, I want to eat more<br />
Want to live fine, want luxury and peace<br />
With peace and tranquility</i>
<br />
From <i>War</i>, Neville Marcano (Growling Tiger) with Lord Iere and Indian Prince. Other tracks here by Brendan Behan, John Bray, Eric Bentley, Merle Haggard, and some Alan Lomax recordings selected by Nathan Salsburg.
