Goodbye Dear Old Stepstone: Janette Carter 
<br />
<small>First broadcast March 6, 2006</small> 
<br /><br />
Nathan Salsburg's tribute to Janette Carter (1923-2006) and the music of Southwestern Virginia. Featuring the Carter Family, Wayne Henderson, Kelly Harrell and the Virginia String Band, Virginia Playboys, Norman Edmonds and the Old-Timers, E. C. Ball and the Friendly Gospel Singers, others.
