Dub is so comforting in times of war and strife drawing in the Bob
Marley feelings of 'everything is going to be alright'.  Rhythm and
Culture presents the first release from Second Sky. Aram Scaram the
host of a long standing Reggae radio show in Toronto releases
"Trouble" under his moniker Citizen Sound.  New York's Redbud Records
and Bastard Jazz always unearth hidden gems keeping vinyl alive.  Six
Degrees Records has a consistent release of world music fused with
electronics like <a href="http://myspace.com/gaudimusic">Gaudi's</a> latest "Brainwashed"
and the awesome Bombay Dub Orchestra.  Also enjoy Agape featuring
<a href="http://myspace.com/agapefeaturingnadiaharris">Nadia Harris</a> out of Miami with
her dub band, Miguel Graca out of Montreal with his dubbed out talking
drum and <a href="http://fourtet.net">Four Tet's</a> latest electronic 'ping
ponger'.<br /><br />

With much gratitude to the labels behind these artists: <a href="http://rhythmandculture.com">Rhythm and
Culture</a>, Balance, <a href="http://www.redbudrecords.com">Redbud</a>, <a href="http://www.sixdegreesrecords.com">Six Degrees</a>, <a href="http://www.bastardjazz.com">Bastard Jazz</a>
