<b>RecifeNation: <i>Mangue, Music & Mud</i></b><br/>
In this fifth edition of <i>Sonoridade</i>, producer Béco Dranoff presents a
broad overview on <b>Mangue Beat</b>, the influential cultural movement
that took the city of <b>Recife</b> (the capital of the northeastern state of
Pernambuco) by storm in the early 90's. Artists and bands such as
Chico Science & Nação Zumbí, Mundo Livre S/A, DJ Dolores, Otto and
many more, were the epicenter of  the most important music and art
movement since the Tropicália heyday in the late 60's. 
<br/><br/>
The Mangue scene released a <i>manifesto</i> introducing the unlikely concept of the
link between crabs (abundant in the swamps of this river/ocean city)
and the powerful satellite antennas delivering waves of international
pop culture. This highly original movement changed the face of
Brazilian pop music forever, bringing into the mainstream the fresh
mix of northern folk rhythms as Maracatú, Forró, Embolada, Côco,
religious chants with rock, dub, electronica, making it 'cool' for
kids to enjoy and explore Brazilian roots rhythms. Feel the <i>Mangue
Power</i>!!
